# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/schuellerf/pre-commit-pyspelling
    rev: 0.1.0
    hooks:
      - id: pyspelling
        args: ["--config", ".spellcheck.yml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - PyYAML
          - types-PyYAML
          - types-requests
          - fastmcp
          - requests
          - PyJWT
          - deepeval
          - llama-index
          - llama-index-core
          - llama-index-tools-mcp
          - llama-index-llms-openai
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.0
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        # always pass all classes, otherwise e.g. tests fail
        pass_filenames: false
        args: [--recursive=y, .]
        additional_dependencies:
          - PyYAML
          - types-PyYAML
          - types-requests
          - pytest
          - fastmcp
          - requests
          - PyJWT
          - deepeval
          - llama-index
          - llama-index-core
          - llama-index-tools-mcp
          - llama-index-llms-openai
