name: Build and Push Container Image

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static

      - name: Build
        run: |
          podman build --platform=linux/amd64,linux/arm64 --jobs=2 --manifest ib-mcp .

      - name: Generate tag
        id: tag
        run: |
          TAG=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::8}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $ --password-stdin
          podman manifest push --all --format v2s2 ib-mcp ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
          podman manifest push --all --format v2s2 ib-mcp ghcr.io/${{ github.repository }}:latest

  build-release-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag
        id: tag
        run: |
          TAG=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::8}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build claude extension
        env:
          TAG: ${{ steps.tag.outputs.tag }}
        run: make build-claude-extension

      - name: Create release with assets
        env:
          TAG: ${{ steps.tag.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG" \
            --title "Release $TAG" \
            --generate-notes \
            image-builder-"$TAG".cdx
