name: Build and Push Container Image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static

      - name: Build
        run: |
          podman build --platform=linux/amd64,linux/arm64 --jobs=2 --manifest ib-mcp .

      - name: Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $ --password-stdin
          podman manifest push --all --format v2s2 ib-mcp ghcr.io/${{ github.repository }}:${{ github.sha }}
          podman manifest push --all --format v2s2 ib-mcp ghcr.io/${{ github.repository }}:latest
